name: headlines_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  hexcolor: ^2.0.4
  http: ^0.13.3
  skeleton_text: ^3.0.0
  cached_network_image: ^3.1.0
  pull_to_refresh: ^2.0.0
  stream_transform: ^2.0.0
  shared_preferences: ^2.0.6
  share: ^2.0.4
  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.9.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

